# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod download
    - go mod tidy
    - go run github.com/securego/gosec/v2/cmd/gosec@latest -quiet ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
release:
  ids:
    - default
  draft: true
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"
  #  discussion_category_name: General
  prerelease: auto
  mode: replace
  header: |
    ## ⚙️ The `{{ .Tag }}` release
  footer: |
    ## Notes

    > 💡 Check the [`documentation`](https://archimoebius.github.io/hexer/) for usage and more information.

    ## Your help to improve project

    I'd be truly grateful for help with:

    - Creating tests (and/or benchmarks) for code.
    - Improving existing functions, structs, or tests.
    - Feature requests with interesting functions that would be good to add.

    Your PRs & issues are welcome! Thanks 😉

  disable: false
  skip_upload: false

changelog:
  #  use: github
  sort: asc
  abbrev: -1
  filters:
    exclude:
      - "^*.md"
      - "^*.ya?ml"
  groups:
    - title: Features
      regexp: ^.*?(F|f)eature.*?$
      order: 0
    - title: Bug fixes
      regexp: ^.*?((B|b)ug)|((F|f)ix).*?$
      order: 1
    - title: Improvements
      regexp: ^.*?(I|i)mprove.*?$
      order: 2
    - title: Updates
      regexp: ^.*?(U|u)pdate.*?$
      order: 3
    - title: Security issues
      regexp: ^.*?(S|s)ecurity.*?$
      order: 4
    - title: Delete unused or stale
      regexp: ^.*?((D|d)elete)|((U|u)nused)|((S|s)tale).*?$
      order: 5
    - title: Others
      order: 999
